In [34]:
import yfinance as yf
import datetime
import pandas as pd
import matplotlib
import numpy as np
import statsmodels as sm

In [35]:
assets= pd.read_html("https://finance.yahoo.com/crypto/?offset=0&count=100")[0]['Symbol'].values
data = []
asset_names = []

In [6]:
assets

array(['BTC-USD', 'ETH-USD', 'USDT-USD', 'BNB-USD', 'XRP-USD', 'SOL-USD',
       'USDC-USD', 'STETH-USD', 'ADA-USD', 'DOGE-USD', 'TRX-USD',
       'WTRX-USD', 'LINK-USD', 'TON11419-USD', 'AVAX-USD', 'MATIC-USD',
       'DOT-USD', 'WBTC-USD', 'DAI-USD', 'LTC-USD', 'SHIB-USD',
       'WEOS-USD', 'BCH-USD', 'UNI7083-USD', 'ATOM-USD'], dtype=object)

In [7]:
for asset in assets:
    data.append(yf.download(asset, period = "8y"))

[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed
[*********************100%%**********************]  1 of 1 completed

In [8]:
data

[                    Open          High           Low         Close  \
 Date
 2015-12-03    359.330994    370.274994    357.411987    361.045990
 2015-12-04    361.261993    363.515991    355.756989    363.183014
 2015-12-05    363.721008    389.785004    363.229004    388.949005
 2015-12-06    389.554993    402.808990    387.088989    388.782990
 2015-12-07    389.977997    399.968994    385.411011    395.536011
 ...                  ...           ...           ...           ...
 2023-11-29  37826.105469  38366.113281  37612.632812  37858.492188
 2023-11-30  37861.117188  38141.753906  37531.140625  37712.746094
 2023-12-01  37718.007812  38954.109375  37629.359375  38688.750000
 2023-12-02  38689.277344  39678.937500  38652.593750  39476.332031
 2023-12-03  39472.207031  39634.808594  39309.335938  39614.953125

                Adj Close       Volume
 Date
 2015-12-03    361.045990     50714900
 2015-12-04    363.183014     35784100
 2015-12-05    388.949005     66282200
 2015-12-06    388.782990     77762000
 2015-12-07    395.536011     63455800
 ...                  ...          ...
 2023-11-29  37858.492188  20728546658
 2023-11-30  37712.746094  18115982627
 2023-12-01  38688.750000  23512784002
 2023-12-02  39476.332031  15534035612
 2023-12-03  39614.953125  16352571392

 [2923 rows x 6 columns],
                    Open         High          Low        Close    Adj Close  \
 Date
 2017-11-09   308.644989   329.451996   307.056000   320.884003   320.884003
 2017-11-10   320.670990   324.717987   294.541992   299.252991   299.252991
 2017-11-11   298.585999   319.453003   298.191986   314.681000   314.681000
 2017-11-12   314.690002   319.153015   298.513000   307.907990   307.907990
 2017-11-13   307.024994   328.415009   307.024994   316.716003   316.716003
 ...                 ...          ...          ...          ...          ...
 2023-11-29  2049.186768  2071.994385  2020.756592  2029.929199  2029.929199
 2023-11-30  2029.358398  2054.444336  2022.461792  2052.556152  2052.556152
 2023-12-01  2052.096680  2109.319092  2046.557007  2087.139893  2087.139893
 2023-12-02  2087.663574  2182.817871  2087.407959  2165.704102  2165.704102
 2023-12-03  2165.895752  2177.665039  2151.720947  2162.450928  2162.450928

                  Volume
 Date
 2017-11-09    893249984
 2017-11-10    885985984
 2017-11-11    842300992
 2017-11-12   1613479936
 2017-11-13   1041889984
 ...                 ...
 2023-11-29   8945151861
 2023-11-30   8107789163
 2023-12-01  10866891430
 2023-12-02   9130124831
 2023-12-03  10000390144

 [2216 rows x 6 columns],
                 Open      High       Low     Close  Adj Close       Volume
 Date
 2017-11-09  1.010870  1.013270  0.996515  1.008180   1.008180    358188000
 2017-11-10  1.006500  1.024230  0.995486  1.006010   1.006010    756446016
 2017-11-11  1.005980  1.026210  0.995799  1.008990   1.008990    746227968
 2017-11-12  1.006020  1.105910  0.967601  1.012470   1.012470   1466060032
 2017-11-13  1.004480  1.029290  0.975103  1.009350   1.009350    767884032
 ...              ...       ...       ...       ...        ...          ...
 2023-11-29  1.000326  1.000817  0.999889  1.000220   1.000220  35115076722
 2023-11-30  1.000236  1.000390  0.999863  1.000156   1.000156  29247809691
 2023-12-01  1.000196  1.000630  0.999831  1.000185   1.000185  36738335582
 2023-12-02  1.000199  1.000561  0.999693  1.000364   1.000364  31086578261
 2023-12-03  1.000444  1.000554  0.999650  1.000010   1.000010  33977094144

 [2216 rows x 6 columns],
                   Open        High         Low       Close   Adj Close  \
 Date
 2017-11-09    2.053140    2.174230    1.893940    1.990770    1.990770
 2017-11-10    2.007730    2.069470    1.644780    1.796840    1.796840
 2017-11-11    1.786280    1.917750    1.614290    1.670470    1.670470
 2017-11-12    1.668890    1.672800    1.462560    1.519690    1.519690
 2017-11-13    1.526010    1.735020    1.517600    1.686620    1.686620
 ...                ...         ...         ...         ...         ...
 2023-11-29  229.693237  231.197449  226.519440  227.342758  227.342758
 2023-11-30  227.343033  229.143967  226.226547  227.683807  227.683807
 2023-12-01  227.688812  229.891068  227.232666  228.545639  228.545639
 2023-12-02  228.538559  230.034302  226.689606  229.300842  229.300842
 2023-12-03  229.289536  231.552643  227.038559  227.938965  227.938965

                Volume
 Date
 2017-11-09   19192200
 2017-11-10   11155000
 2017-11-11    8178150
 2017-11-12   15298700
 2017-11-13   12238800
 ...               ...
 2023-11-29  602240832
 2023-11-30  572448874
 2023-12-01  611750028
 2023-12-02  628871423
 2023-12-03  686988864

 [2216 rows x 6 columns],
                 Open      High       Low     Close  Adj Close      Volume
 Date
 2017-11-09  0.217911  0.221791  0.214866  0.217488   0.217488   147916992
 2017-11-10  0.218256  0.219068  0.205260  0.206483   0.206483   141032992
 2017-11-11  0.205948  0.214456  0.205459  0.210430   0.210430   134503008
 2017-11-12  0.210214  0.210214  0.195389  0.197339   0.197339   251175008
 2017-11-13  0.197472  0.204081  0.197456  0.203442   0.203442   132567000
 ...              ...       ...       ...       ...        ...         ...
 2023-11-29  0.611410  0.616510  0.605113  0.609358   0.609358  1007163957
 2023-11-30  0.609355  0.609632  0.599816  0.606358   0.606358   980182657
 2023-12-01  0.606350  0.613993  0.604386  0.612915   0.612915   919121548
 2023-12-02  0.612914  0.622459  0.611746  0.620976   0.620976   667809511
 2023-12-03  0.620998  0.631425  0.618290  0.626867   0.626867   967586432

 [2216 rows x 6 columns],
                  Open       High        Low      Close  Adj Close      Volume
 Date
 2020-04-10   0.832005   1.313487   0.694187   0.951054   0.951054    87364276
 2020-04-11   0.951054   1.049073   0.765020   0.776819   0.776819    43862444
 2020-04-12   0.785448   0.956670   0.762426   0.882507   0.882507    38736897
 2020-04-13   0.890760   0.891603   0.773976   0.777832   0.777832    18211285
 2020-04-14   0.777832   0.796472   0.628169   0.661925   0.661925    16747614
 ...               ...        ...        ...        ...        ...         ...
 2023-11-29  58.193050  61.653358  57.855091  59.250130  59.250130  1941361674
 2023-11-30  59.253517  61.437874  58.946922  59.241623  59.241623  1263841021
 2023-12-01  59.238178  61.758018  58.778210  59.803997  59.803997  1376669760
 2023-12-02  59.803745  63.832859  59.773762  63.832859  63.832859  1346327049
 2023-12-03  63.820877  65.381752  62.627781  63.328575  63.328575  1483982720

 [1333 rows x 6 columns],
                 Open      High       Low     Close  Adj Close      Volume
 Date
 2018-10-08  1.004100  1.007680  1.001900  1.002210   1.002210      382900
 2018-10-09  1.004270  1.008330  1.000030  1.006860   1.006860      108803
 2018-10-10  1.004940  1.019080  1.003970  1.009620   1.009620      711783
 2018-10-11  1.009940  1.031230  1.001730  1.009780   1.009780     4177290
 2018-10-12  1.008610  1.018710  1.001140  1.012720   1.012720     1322240
 ...              ...       ...       ...       ...        ...         ...
 2023-11-29  0.999853  1.000228  0.999323  1.000040   1.000040  4806411317
 2023-11-30  1.000022  1.000288  0.999791  1.000006   1.000006  3955267282
 2023-12-01  1.000093  1.000207  0.999496  0.999797   0.999797  5045550334
 2023-12-02  0.999751  1.000115  0.999320  0.999953   0.999953  3627380584
 2023-12-03  0.999966  1.000132  0.999293  0.999818   0.999818  3814704384

 [1883 rows x 6 columns],
                    Open         High          Low        Close    Adj Close  \
 Date
 2020-12-23   594.087341   617.949280   564.958862   588.655334   588.655334
 2020-12-24   588.686462   613.328125   551.784607   611.787476   611.787476
 2020-12-25   611.759033   626.397217   600.420532   626.136230   626.136230
 2020-12-26   626.150024   642.746277   610.427185   627.472473   627.472473
 2020-12-27   627.465454   707.751221   617.719788   682.467163   682.467163
 ...                 ...          ...          ...          ...          ...
 2023-11-29  2044.627197  2069.847168  2020.799316  2027.640869  2027.640869
 2023-11-30  2027.725952  2046.032104  2023.683838  2045.652100  2045.652100
 2023-12-01  2045.526855  2096.754150  2041.796997  2080.591797  2080.591797
 2023-12-02  2080.428711  2165.037598  2080.428711  2158.363037  2158.363037
 2023-12-03  2158.658691  2168.106934  2145.209229  2156.314941  2156.314941

               Volume
 Date
 2020-12-23     64860
 2020-12-24     53526
 2020-12-25     45601
 2020-12-26     10297
 2020-12-27     90078
 ...              ...
 2023-11-29   3914119
 2023-11-30   8881258
 2023-12-01  23736427
 2023-12-02   8048591
 2023-12-03  13818006

 [1076 rows x 6 columns],
                 Open      High       Low     Close  Adj Close     Volume
 Date
 2017-11-09  0.025160  0.035060  0.025006  0.032053   0.032053   18716200
 2017-11-10  0.032219  0.033348  0.026451  0.027119   0.027119    6766780
 2017-11-11  0.026891  0.029659  0.025684  0.027437   0.027437    5532220
 2017-11-12  0.027480  0.027952  0.022591  0.023977   0.023977    7280250
 2017-11-13  0.024364  0.026300  0.023495  0.025808   0.025808    4419440
 ...              ...       ...       ...       ...        ...        ...
 2023-11-29  0.385633  0.388801  0.378548  0.381776   0.381776  256880751
 2023-11-30  0.381803  0.382576  0.372702  0.375895   0.375895  267025029
 2023-12-01  0.375891  0.385247  0.374483  0.384202   0.384202  248849205
 2023-12-02  0.384204  0.397844  0.383415  0.397798   0.397798  255637811
 2023-12-03  0.397821  0.402284  0.390867  0.392914   0.392914  316350240

 [2216 rows x 6 columns],
                 Open      High       Low     Close  Adj Close     Volume
 Date
 2017-11-09  0.001207  0.001415  0.001181  0.001415   0.001415    6259550
 2017-11-10  0.001421  0.001431  0.001125  0.001163   0.001163    4246520
 2017-11-11  0.001146  0.001257  0.001141  0.001201   0.001201    2231080
 2017-11-12  0.001189  0.001210  0.001002  0.001038   0.001038    3288960
 2017-11-13  0.001046  0.001212  0.001019  0.001211   0.001211    2481270
 ...              ...       ...       ...       ...        ...        ...
 2023-11-29  0.081004  0.082842  0.079786  0.080593   0.080593  596560786
 2023-11-30  0.080599  0.084217  0.080537  0.083417   0.083417  645565938
 2023-12-01  0.083414  0.084908  0.082504  0.083857   0.083857  519429439
 2023-12-02  0.083856  0.086481  0.083548  0.086279   0.086279  462433973
 2023-12-03  0.086283  0.087147  0.084257  0.084601   0.084601  559389248

 [2216 rows x 6 columns],
                 Open      High       Low     Close  Adj Close     Volume
 Date
 2017-11-09  0.002304  0.002438  0.002285  0.002344   0.002344    2924350
 2017-11-10  0.002335  0.002350  0.001989  0.002013   0.002013    2193620
 2017-11-11  0.002026  0.002298  0.001890  0.002003   0.002003    1748460
 2017-11-12  0.002006  0.002006  0.001684  0.001783   0.001783    2174370
 2017-11-13  0.001795  0.002146  0.001771  0.002112   0.002112    2889150
 ...              ...       ...       ...       ...        ...        ...
 2023-11-29  0.103041  0.104053  0.102928  0.103544   0.103544  238729774
 2023-11-30  0.103542  0.104236  0.103020  0.103515   0.103515  237850679
 2023-12-01  0.103514  0.104130  0.102889  0.103177   0.103177  221433774
 2023-12-02  0.103178  0.103538  0.102492  0.103286   0.103286  185994290
 2023-12-03  0.103296  0.103683  0.102822  0.103019   0.103019  191214176

 [2216 rows x 6 columns],
                 Open      High       Low     Close  Adj Close   Volume
 Date
 2022-03-05  0.060484  0.060734  0.060390  0.060396   0.060396  1242664
 2022-03-06  0.060396  0.060712  0.058954  0.058955   0.058955  1147624
 2022-03-07  0.058956  0.060431  0.058014  0.058566   0.058566  1896907
 2022-03-08  0.058564  0.060910  0.058564  0.060757   0.060757  1658131
 2022-03-09  0.060757  0.062442  0.060578  0.060668   0.060668  2175214
 ...              ...       ...       ...       ...        ...      ...
 2023-11-29  0.102941  0.103648  0.102678  0.103063   0.103063  1793977
 2023-11-30  0.103039  0.104102  0.101250  0.101685   0.101685  1749298
 2023-12-01  0.101679  0.103628  0.101071  0.103175   0.103175   823197
 2023-12-02  0.103172  0.103468  0.102622  0.103179   0.103179   649849
 2023-12-03  0.103181  0.103410  0.102858  0.103001   0.103001   638704

 [639 rows x 6 columns],
                  Open       High        Low      Close  Adj Close     Volume
 Date
 2017-11-09   0.216713   0.248233   0.195411   0.223969   0.223969    3347920
 2017-11-10   0.224700   0.231280   0.180161   0.187602   0.187602    2125460
 2017-11-11   0.186398   0.197687   0.166026   0.179770   0.179770    2238980
 2017-11-12   0.179667   0.198376   0.145948   0.170898   0.170898    5455200
 2017-11-13   0.169117   0.205014   0.168743   0.183071   0.183071    2992650
 ...               ...        ...        ...        ...        ...        ...
 2023-11-29  14.519965  14.959171  14.450841  14.511725  14.511725  535989113
 2023-11-30  14.512963  14.794313  14.309827  14.404431  14.404431  519218596
 2023-12-01  14.404645  15.015858  14.309395  14.983229  14.983229  515864142
 2023-12-02  14.982871  16.168455  14.940643  15.994241  15.994241  693342917
 2023-12-03  15.993650  16.237858  15.853576  15.997462  15.997462  620130496

 [2216 rows x 6 columns],
                 Open      High       Low     Close  Adj Close    Volume
 Date
 2021-08-27  0.519893  0.687477  0.498175  0.686748   0.686748    573566
 2021-08-28  0.686766  0.691065  0.606474  0.640526   0.640526    250158
 2021-08-29  0.640724  0.648018  0.527709  0.548201   0.548201    188295
 2021-08-30  0.548234  0.915924  0.547050  0.868268   0.868268    763243
 2021-08-31  0.869410  1.132030  0.795093  1.034563   1.034563   1802341
 ...              ...       ...       ...       ...        ...       ...
 2023-11-29  2.437800  2.457136  2.401836  2.427498   2.427498  40770292
 2023-11-30  2.427457  2.448864  2.387345  2.388499   2.388499  31516415
 2023-12-01  2.388556  2.430389  2.381064  2.422211   2.422211  32651022
 2023-12-02  2.422084  2.457583  2.395779  2.432158   2.432158  35298715
 2023-12-03  2.432116  2.452061  2.402001  2.419737   2.419737  34080248

 [829 rows x 6 columns],
                  Open       High        Low      Close  Adj Close     Volume
 Date
 2020-07-13   4.613968   4.915115   4.481499   4.896294   4.896294      28340
 2020-07-14   4.909865   5.229564   4.762068   4.986754   4.986754       3957
 2020-09-22   4.986754  11.463443   4.125380   5.234632   5.234632  288098840
 2020-09-23   5.321654   5.329310   3.982604   4.118469   4.118469  173091214
 2020-09-24   3.817925   4.751878   3.539887   4.566561   4.566561   96110964
 ...               ...        ...        ...        ...        ...        ...
 2023-11-29  20.656727  21.538052  20.582813  21.086414  21.086414  490900529
 2023-11-30  21.088507  21.480314  20.869585  21.386862  21.386862  389076494
 2023-12-01  21.387300  22.568714  21.153488  21.861374  21.861374  564612277
 2023-12-02  21.861385  22.363955  21.785997  22.241074  22.241074  330816327
 2023-12-03  22.241091  22.691193  21.843609  22.003565  22.003565  347326784

 [1170 rows x 6 columns],
                 Open      High       Low     Close  Adj Close     Volume
 Date
 2019-04-28  0.004521  0.004545  0.004317  0.004421   0.004421    8408136
 2019-04-29  0.004418  0.004492  0.003471  0.003471   0.003471    8267044
 2019-04-30  0.003462  0.005078  0.003458  0.004478   0.004478   25072706
 2019-05-01  0.004440  0.004673  0.004071  0.004374   0.004374   10567352
 2019-05-02  0.004366  0.004700  0.004096  0.004198   0.004198    6714908
 ...              ...       ...       ...       ...        ...        ...
 2023-11-29  0.748281  0.770261  0.744856  0.757697   0.757697  416128091
 2023-11-30  0.757702  0.780666  0.753284  0.762516   0.762516  479493165
 2023-12-01  0.762534  0.799496  0.757177  0.799496   0.799496  499277190
 2023-12-02  0.799480  0.823721  0.797859  0.816216   0.816216  454913954
 2023-12-03  0.816196  0.822647  0.804110  0.808663   0.808663  452742560

 [1681 rows x 6 columns],
                 Open      High       Low     Close  Adj Close     Volume
 Date
 2020-08-20  2.787857  3.077784  2.692896  2.900080   2.900080   48819867
 2020-08-21  2.896923  3.090093  2.730919  2.875028   2.875028   49313137
 2020-08-22  2.878570  4.510613  2.816762  4.484690   4.484690  485801096
 2020-08-23  4.487058  4.487058  3.716271  3.967066   3.967066  320749483
 2020-08-24  3.987413  4.783158  3.812670  4.602614   4.602614  407690171
 ...              ...       ...       ...       ...        ...        ...
 2023-11-29  5.270658  5.370062  5.160088  5.168089   5.168089  184196011
 2023-11-30  5.168111  5.567933  5.128606  5.465794   5.465794  282346044
 2023-12-01  5.466083  5.516275  5.379859  5.475040   5.475040  153997357
 2023-12-02  5.474731  5.597386  5.458980  5.573881   5.573881  128776781
 2023-12-03  5.573408  5.605761  5.450278  5.481021   5.481021  142063808

 [1201 rows x 6 columns],
                     Open          High           Low         Close  \
 Date
 2019-01-30   3494.277588   3502.762939   3477.248047   3496.455322
 2019-01-31   3496.839844   3535.421143   3435.290527   3466.506592
 2019-02-01   3469.393066   3517.770264   3422.825684   3480.772217
 2019-02-02   3476.335205   3546.404297   3459.112793   3542.095459
 2019-02-03   3540.562744   3544.666992   3436.177734   3477.865967
 ...                  ...           ...           ...           ...
 2023-11-29  37758.718750  38227.218750  37626.757812  37756.578125
 2023-11-30  37755.914062  38016.511719  37578.312500  37718.011719
 2023-12-01  37721.347656  38786.722656  37668.210938  38655.781250
 2023-12-02  38657.906250  39538.230469  38638.988281  39422.726562
 2023-12-03  39422.167969  39544.230469  39352.671875  39544.230469

                Adj Close     Volume
 Date
 2019-01-30   3496.455322       1475
 2019-01-31   3466.506592      19289
 2019-02-01   3480.772217      13640
 2019-02-02   3542.095459       1895
 2019-02-03   3477.865967       6525
 ...                  ...        ...
 2023-11-29  37756.578125   74227455
 2023-11-30  37718.011719   63665133
 2023-12-01  38655.781250  111586477
 2023-12-02  39422.726562  120572243
 2023-12-03  39544.230469  128645712

 [1769 rows x 6 columns],
                 Open      High       Low     Close  Adj Close     Volume
 Date
 2019-11-22  0.997358  1.026548  0.972164  0.992598   0.992598    2104541
 2019-11-23  0.992184  1.028747  0.988341  1.016282   1.016282     311283
 2019-11-24  1.016288  1.035136  0.995609  1.002270   1.002270     255060
 2019-11-25  1.001289  1.034708  0.984805  1.007021   1.007021     958777
 2019-11-26  1.007208  1.031428  0.991767  1.006096   1.006096     217385
 ...              ...       ...       ...       ...        ...        ...
 2023-11-29  0.999509  1.000819  0.998564  0.999717   0.999717  314547669
 2023-11-30  0.999773  1.000895  0.998877  1.000063   1.000063  504381554
 2023-12-01  1.000124  1.000749  0.998741  0.999753   0.999753  220472115
 2023-12-02  0.999749  1.001447  0.998846  1.000005   1.000005  310128871
 2023-12-03  0.999967  1.000431  0.998873  0.999710   0.999710  321104384

 [1473 rows x 6 columns],
                  Open       High        Low      Close  Adj Close     Volume
 Date
 2015-12-03   3.346720   3.441070   3.336910   3.377490   3.377490    1943430
 2015-12-04   3.382330   3.387350   3.343740   3.361810   3.361810    1333170
 2015-12-05   3.369940   3.540740   3.369940   3.523720   3.523720    2664550
 2015-12-06   3.525380   3.578420   3.447690   3.473100   3.473100    4063170
 2015-12-07   3.452550   3.691690   3.447110   3.645140   3.645140    4210900
 ...               ...        ...        ...        ...        ...        ...

In [9]:
volume= pd.concat(data, axis = 1)['Volume']
volume.columns = assets

In [10]:
close_price = pd.concat(data, axis = 1)['Close']
close_price.columns = assets

In [11]:
close_price

,BTC-USD,ETH-USD,USDT-USD,BNB-USD,XRP-USD,SOL-USD,USDC-USD,STETH-USD,ADA-USD,DOGE-USD,...,MATIC-USD,DOT-USD,WBTC-USD,DAI-USD,LTC-USD,SHIB-USD,WEOS-USD,BCH-USD,UNI7083-USD,ATOM-USD
Date,,,,,,,,,,,,,,,,,,,,,
2015-12-03,361.045990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.377490,NaN,NaN,NaN,NaN,NaN
2015-12-04,363.183014,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.361810,NaN,NaN,NaN,NaN,NaN
2015-12-05,388.949005,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.523720,NaN,NaN,NaN,NaN,NaN
2015-12-06,388.782990,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.473100,NaN,NaN,NaN,NaN,NaN
2015-12-07,395.536011,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,3.645140,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-11-29,37858.492188,2029.929199,1.000220,227.342758,0.609358,59.250130,1.000040,2027.640869,0.381776,0.080593,...,0.757697,5.168089,37756.578125,0.999717,69.989349,0.000008,4.449729,223.293594,6.021174,9.220939
2023-11-30,37712.746094,2052.556152,1.000156,227.683807,0.606358,59.241623,1.000006,2045.652100,0.375895,0.083417,...,0.762516,5.465794,37718.011719,1.000063,69.445580,0.000008,4.295294,221.581909,5.951752,9.255597
2023-12-01,38688.750000,2087.139893,1.000185,228.545639,0.612915,59.803997,0.999797,2080.591797,0.384202,0.083857,...,0.799496,5.475040,38655.781250,0.999753,71.544968,0.000008,4.295466,225.216858,6.018907,9.462127
2023-12-02,39476.332031,2165.704102,1.000364,229.300842,0.620976,63.832859,0.999953,2158.363037,0.397798,0.086279,...,0.816216,5.573881,39422.726562,1.000005,72.272224,0.000009,4.328868,228.185135,6.171488,9.640365
2023-12-03,39614.953125,2162.450928,1.000010,227.938965,0.626867,63.328575,0.999818,2156.314941,0.392914,0.084601,...,0.808663,5.481021,39544.230469,0.999710,71.904778,0.000008,4.461243,226.218063,6.127890,9.483405

In [15]:
returns = close_price.copy()
for i in np.arange(0,len(close_price)):
    if i == 0:
        returns.iloc[i]= 0
    else:
        returns.iloc[i]= np.log(close_price.iloc[i]/close_price.iloc[i-1])
# returns.drop("2015-08-10", inplace=True)

In [13]:
returns['BTC-USD'].ewm(span=len(returns['BTC-USD'])).std().plot()

NameError: name 'returns' is not defined

In [17]:
returns.describe()

C:\Crypto_Price_Action\envCPA\lib\site-packages\pandas\core\nanops.py:1010: RuntimeWarning: invalid value encountered in subtract
  sqr = _ensure_numeric((avg - values) ** 2)

,BTC-USD,ETH-USD,USDT-USD,BNB-USD,XRP-USD,SOL-USD,USDC-USD,STETH-USD,ADA-USD,DOGE-USD,...,MATIC-USD,DOT-USD,WBTC-USD,DAI-USD,LTC-USD,SHIB-USD,WEOS-USD,BCH-USD,UNI7083-USD,ATOM-USD
count,2923.000000,2216.000000,2216.000000,2216.000000,2216.000000,1333.000000,1883.000000,1076.000000,2216.000000,2216.000000,...,1681.000000,1201.000000,1769.000000,1473.000000,2923.000000,963.000000,203.000000,2216.000000,1172.000000,1726.000000
mean,0.001607,0.000861,-0.000004,0.002139,0.000478,0.003150,-0.000001,0.001207,0.001131,0.001846,...,0.003099,0.000530,0.001371,0.000005,0.001046,inf,0.007945,-0.000479,-0.000101,0.000216
std,0.037532,0.048225,0.004127,0.054765,0.060900,0.072740,0.003454,0.044349,0.063176,0.073237,...,0.077225,0.058555,0.037340,0.006457,0.053265,NaN,0.059410,0.061112,0.061150,0.064692
min,-0.464730,-0.550732,-0.052570,-0.543084,-0.550503,-0.549582,-0.037233,-0.302637,-0.503638,-0.515118,...,-0.715681,-0.476964,-0.480414,-0.090348,-0.449062,-0.693147,-0.253806,-0.561348,-0.403474,-0.590198
25%,-0.012623,-0.019189,-0.000539,-0.018970,-0.021808,-0.032980,-0.000315,-0.017896,-0.026961,-0.022992,...,-0.032340,-0.028588,-0.013124,-0.000579,-0.020426,0.000000,-0.005018,-0.024558,-0.031410,-0.029762
50%,0.001482,0.000755,-0.000006,0.000983,-0.000780,-0.000144,0.000006,0.000931,0.000103,-0.000433,...,0.000000,-0.000492,0.000764,-0.000019,0.000095,0.000000,0.000117,-0.000925,-0.000317,0.000522
75%,0.016925,0.023912,0.000540,0.023321,0.019703,0.037454,0.000334,0.021478,0.025707,0.019420,...,0.032407,0.025801,0.016074,0.000567,0.022510,0.000000,0.010647,0.022769,0.028764,0.031716
max,0.225119,0.234741,0.056606,0.529218,0.606885,0.387184,0.042439,0.221414,0.861543,1.516328,...,0.498186,0.444607,0.244310,0.065383,0.511417,inf,0.541427,0.431577,0.380330,0.280929